// ===============================================================
// MC Question Bank - 98 trilingual questions (EN / UZ / RU)
// May 2026 update:
//   - 2 ASCII questions removed on instructor request
//   - Russian translation added to every question and option
//
// At exam time, app.js's selectArrangeAndShuffle picks 15 from
// this bank + 5 from MC_BANK_NEW (snippets/pointers) = 20 total.
// Correct-answer positions are balanced; max 2 consecutive same.
// ===============================================================

window.MC_BANK = [

  // ---- DATA TYPES & TYPE CONVERSION (8 questions, 2 ASCII removed) ----
  {
    en: "Which data type is best for storing a student's GPA like 3.75?",
    uz: "3.75 kabi talabaning GPA sini saqlash uchun qaysi ma'lumot turi eng yaxshi?",
    ru: "Какой тип данных лучше всего подходит для хранения GPA студента, например 3.75?",
    opts: [
      { en: "int", uz: "int", ru: "int" },
      { en: "double", uz: "double", ru: "double" },
      { en: "bool", uz: "bool", ru: "bool" },
      { en: "char", uz: "char", ru: "char" },
    ],
    correct: 1,
  },
  {
    en: "What does <code>const int MAX = 100;</code> mean?",
    uz: "<code>const int MAX = 100;</code> nimani anglatadi?",
    ru: "Что означает <code>const int MAX = 100;</code>?",
    opts: [
      { en: "MAX can change any time", uz: "MAX istalgan vaqtda o'zgarishi mumkin", ru: "MAX можно изменить в любое время" },
      { en: "MAX is 100 and cannot be changed", uz: "MAX 100 ga teng va o'zgartirib bo'lmaydi", ru: "MAX равен 100 и не может быть изменён" },
      { en: "MAX is deleted later", uz: "MAX keyinroq o'chiriladi", ru: "MAX будет удалён позже" },
      { en: "MAX is a function name", uz: "MAX funksiya nomi", ru: "MAX - это имя функции" },
    ],
    correct: 1,
  },
  {
    en: "What value does <code>int x = 7 / 2;</code> store in x?",
    uz: "<code>int x = 7 / 2;</code> x ga qanday qiymat saqlaydi?",
    ru: "Какое значение присваивается переменной x в <code>int x = 7 / 2;</code>?",
    opts: [
      { en: "3.5", uz: "3.5", ru: "3.5" },
      { en: "4", uz: "4", ru: "4" },
      { en: "3", uz: "3", ru: "3" },
      { en: "3.0", uz: "3.0", ru: "3.0" },
    ],
    correct: 2,
  },
  {
    en: "Which conversion is EXPLICIT in C++?",
    uz: "C++ da qaysi tur almashtiruvi ANIQ (explicit)?",
    ru: "Какое преобразование является ЯВНЫМ (explicit) в C++?",
    opts: [
      { en: "int x = 3.5;", uz: "int x = 3.5;", ru: "int x = 3.5;" },
      { en: "double y = 5;", uz: "double y = 5;", ru: "double y = 5;" },
      { en: "int x = static_cast<int>(3.5);", uz: "int x = static_cast<int>(3.5);", ru: "int x = static_cast<int>(3.5);" },
      { en: "char c = 65;", uz: "char c = 65;", ru: "char c = 65;" },
    ],
    correct: 2,
  },
  {
    en: "What does <code>bool</code> store?",
    uz: "<code>bool</code> nimani saqlaydi?",
    ru: "Что хранит тип <code>bool</code>?",
    opts: [
      { en: "Numbers only", uz: "Faqat sonlar", ru: "Только числа" },
      { en: "Letters only", uz: "Faqat harflar", ru: "Только буквы" },
      { en: "Any value", uz: "Istalgan qiymat", ru: "Любое значение" },
      { en: "true or false", uz: "true yoki false", ru: "true или false" },
    ],
    correct: 3,
  },
  {
    en: "What happens with <code>double d = 3.7; int i = d;</code>?",
    uz: "<code>double d = 3.7; int i = d;</code> nima sodir bo'ladi?",
    ru: "Что происходит при <code>double d = 3.7; int i = d;</code>?",
    opts: [
      { en: "Compile error", uz: "Kompilyatsiya xatosi", ru: "Ошибка компиляции" },
      { en: "i becomes 3 (truncated)", uz: "i 3 bo'ladi (kesilgan)", ru: "i становится 3 (отбрасывание дробной)" },
      { en: "i becomes 4 (rounded)", uz: "i 4 bo'ladi (yaxlitlangan)", ru: "i становится 4 (округление)" },
      { en: "i becomes 3.7", uz: "i 3.7 bo'ladi", ru: "i становится 3.7" },
    ],
    correct: 1,
  },
  {
    en: "Which is the BEST type for a person's age (0-120)?",
    uz: "Inson yoshi (0-120) uchun ENG YAXSHI tur qaysi?",
    ru: "Какой тип ЛУЧШЕ всего подходит для возраста человека (0-120)?",
    opts: [
      { en: "double", uz: "double", ru: "double" },
      { en: "string", uz: "string", ru: "string" },
      { en: "int", uz: "int", ru: "int" },
      { en: "bool", uz: "bool", ru: "bool" },
    ],
    correct: 2,
  },
  {
    en: "What does <code>auto x = 3.14;</code> deduce <code>x</code> as?",
    uz: "<code>auto x = 3.14;</code> da <code>x</code> qaysi tur sifatida aniqlanadi?",
    ru: "Какой тип будет определён для <code>x</code> в <code>auto x = 3.14;</code>?",
    opts: [
      { en: "int", uz: "int", ru: "int" },
      { en: "double", uz: "double", ru: "double" },
      { en: "float", uz: "float", ru: "float" },
      { en: "char", uz: "char", ru: "char" },
    ],
    correct: 1,
  },

  // ---- OPERATORS (10 questions) ----
  {
    en: "What is the result of <code>10 % 3</code>?",
    uz: "<code>10 % 3</code> natijasi nima?",
    ru: "Каков результат <code>10 % 3</code>?",
    opts: [
      { en: "3", uz: "3", ru: "3" },
      { en: "3.33", uz: "3.33", ru: "3.33" },
      { en: "1", uz: "1", ru: "1" },
      { en: "0", uz: "0", ru: "0" },
    ],
    correct: 2,
  },
  {
    en: "Which operator gives the remainder?",
    uz: "Qaysi operator qoldiqni beradi?",
    ru: "Какой оператор возвращает остаток от деления?",
    opts: [
      { en: "/", uz: "/", ru: "/" },
      { en: "%", uz: "%", ru: "%" },
      { en: "*", uz: "*", ru: "*" },
      { en: "//", uz: "//", ru: "//" },
    ],
    correct: 1,
  },
  {
    en: "What does <code>x++</code> do?",
    uz: "<code>x++</code> nima qiladi?",
    ru: "Что делает <code>x++</code>?",
    opts: [
      { en: "Sets x to 0", uz: "x ni 0 ga o'rnatadi", ru: "Устанавливает x в 0" },
      { en: "Adds 1 to x", uz: "x ga 1 qo'shadi", ru: "Прибавляет 1 к x" },
      { en: "Subtracts 1 from x", uz: "x dan 1 ayiradi", ru: "Вычитает 1 из x" },
      { en: "Doubles x", uz: "x ni ikki barobar oshiradi", ru: "Удваивает x" },
    ],
    correct: 1,
  },
  {
    en: "Which is the logical AND operator?",
    uz: "Mantiqiy AND operatori qaysi?",
    ru: "Какой оператор является логическим AND?",
    opts: [
      { en: "&", uz: "&", ru: "&" },
      { en: "&&", uz: "&&", ru: "&&" },
      { en: "AND", uz: "AND", ru: "AND" },
      { en: "and_", uz: "and_", ru: "and_" },
    ],
    correct: 1,
  },
  {
    en: "What is <code>5 == 5</code>?",
    uz: "<code>5 == 5</code> nima?",
    ru: "Чему равно <code>5 == 5</code>?",
    opts: [
      { en: "true", uz: "true", ru: "true" },
      { en: "false", uz: "false", ru: "false" },
      { en: "Error", uz: "Xato", ru: "Ошибка" },
      { en: "5", uz: "5", ru: "5" },
    ],
    correct: 0,
  },
  {
    en: "Which assigns 10 to x?",
    uz: "Qaysi x ga 10 ni tayinlaydi?",
    ru: "Что присваивает x значение 10?",
    opts: [
      { en: "x == 10;", uz: "x == 10;", ru: "x == 10;" },
      { en: "x := 10;", uz: "x := 10;", ru: "x := 10;" },
      { en: "x = 10;", uz: "x = 10;", ru: "x = 10;" },
      { en: "x -> 10;", uz: "x -> 10;", ru: "x -> 10;" },
    ],
    correct: 2,
  },
  {
    en: "What does <code>!true</code> evaluate to?",
    uz: "<code>!true</code> nimaga teng?",
    ru: "Чему равно <code>!true</code>?",
    opts: [
      { en: "true", uz: "true", ru: "true" },
      { en: "1", uz: "1", ru: "1" },
      { en: "Error", uz: "Xato", ru: "Ошибка" },
      { en: "false", uz: "false", ru: "false" },
    ],
    correct: 3,
  },
  {
    en: "What is <code>(5 > 3) && (2 > 1)</code>?",
    uz: "<code>(5 > 3) && (2 > 1)</code> nima?",
    ru: "Чему равно <code>(5 > 3) && (2 > 1)</code>?",
    opts: [
      { en: "false", uz: "false", ru: "false" },
      { en: "Error", uz: "Xato", ru: "Ошибка" },
      { en: "true", uz: "true", ru: "true" },
      { en: "0", uz: "0", ru: "0" },
    ],
    correct: 2,
  },
  {
    en: "Which is the modulus operator in C++?",
    uz: "C++ da modul operatori qaysi?",
    ru: "Какой оператор является оператором деления по модулю в C++?",
    opts: [
      { en: "mod", uz: "mod", ru: "mod" },
      { en: "//", uz: "//", ru: "//" },
      { en: "%", uz: "%", ru: "%" },
      { en: "rem", uz: "rem", ru: "rem" },
    ],
    correct: 2,
  },
  {
    en: "What does <code>x += 5</code> mean?",
    uz: "<code>x += 5</code> nimani anglatadi?",
    ru: "Что означает <code>x += 5</code>?",
    opts: [
      { en: "x = 5", uz: "x = 5", ru: "x = 5" },
      { en: "x = x + 5", uz: "x = x + 5", ru: "x = x + 5" },
      { en: "x = x * 5", uz: "x = x * 5", ru: "x = x * 5" },
      { en: "x = 5 - x", uz: "x = 5 - x", ru: "x = 5 - x" },
    ],
    correct: 1,
  },

  // ---- CONTROL FLOW / IF-ELSE (10 questions) ----
  {
    en: "Which is the correct syntax for if-else?",
    uz: "if-else uchun to'g'ri sintaksis qaysi?",
    ru: "Какой правильный синтаксис if-else?",
    opts: [
      { en: "if x > 0 then ... else", uz: "if x > 0 then ... else", ru: "if x > 0 then ... else" },
      { en: "if (x > 0) {} else {}", uz: "if (x > 0) {} else {}", ru: "if (x > 0) {} else {}" },
      { en: "when (x > 0) {} else {}", uz: "when (x > 0) {} else {}", ru: "when (x > 0) {} else {}" },
      { en: "if x > 0: ... else:", uz: "if x > 0: ... else:", ru: "if x > 0: ... else:" },
    ],
    correct: 1,
  },
  {
    en: "What does <code>if (x == 5)</code> check?",
    uz: "<code>if (x == 5)</code> nimani tekshiradi?",
    ru: "Что проверяет <code>if (x == 5)</code>?",
    opts: [
      { en: "Assigns 5 to x", uz: "x ga 5 ni tayinlaydi", ru: "Присваивает x значение 5" },
      { en: "Compares x to 5", uz: "x ni 5 bilan solishtiradi", ru: "Сравнивает x с 5" },
      { en: "Sets x to 5", uz: "x ni 5 ga o'rnatadi", ru: "Устанавливает x в 5" },
      { en: "Adds 5 to x", uz: "x ga 5 qo'shadi", ru: "Прибавляет 5 к x" },
    ],
    correct: 1,
  },
  {
    en: "Output: <code>int n = 5; if (n > 3) cout << \"big\"; else cout << \"small\";</code>",
    uz: "Natija: <code>int n = 5; if (n > 3) cout << \"big\"; else cout << \"small\";</code>",
    ru: "Что выведет: <code>int n = 5; if (n > 3) cout << \"big\"; else cout << \"small\";</code>",
    opts: [
      { en: "big", uz: "big", ru: "big" },
      { en: "small", uz: "small", ru: "small" },
      { en: "bigsmall", uz: "bigsmall", ru: "bigsmall" },
      { en: "Nothing", uz: "Hech narsa", ru: "Ничего" },
    ],
    correct: 0,
  },
  {
    en: "What is missing? <code>if (a > 5) { cout << \"yes\"; ___ { cout << \"no\"; }</code>",
    uz: "Nima yetishmaydi? <code>if (a > 5) { cout << \"yes\"; ___ { cout << \"no\"; }</code>",
    ru: "Что пропущено? <code>if (a > 5) { cout << \"yes\"; ___ { cout << \"no\"; }</code>",
    opts: [
      { en: "else", uz: "else", ru: "else" },
      { en: "then", uz: "then", ru: "then" },
      { en: "otherwise", uz: "otherwise", ru: "otherwise" },
      { en: "elif", uz: "elif", ru: "elif" },
    ],
    correct: 0,
  },
  {
    en: "How many <code>else if</code> branches can you have?",
    uz: "Nechta <code>else if</code> filiali bo'lishi mumkin?",
    ru: "Сколько ветвей <code>else if</code> можно иметь?",
    opts: [
      { en: "Maximum 1", uz: "Maksimum 1", ru: "Максимум 1" },
      { en: "Maximum 5", uz: "Maksimum 5", ru: "Максимум 5" },
      { en: "As many as needed", uz: "Kerakli darajada", ru: "Сколько угодно" },
      { en: "Maximum 10", uz: "Maksimum 10", ru: "Максимум 10" },
    ],
    correct: 2,
  },
  {
    en: "When is the body of <code>if (false)</code> executed?",
    uz: "<code>if (false)</code> tanasi qachon bajariladi?",
    ru: "Когда выполняется тело <code>if (false)</code>?",
    opts: [
      { en: "Always", uz: "Har doim", ru: "Всегда" },
      { en: "Never", uz: "Hech qachon", ru: "Никогда" },
      { en: "Sometimes", uz: "Ba'zan", ru: "Иногда" },
      { en: "Once", uz: "Bir marta", ru: "Один раз" },
    ],
    correct: 1,
  },
  {
    en: "What does this print? <code>int x = 0; if (x) cout << \"A\"; else cout << \"B\";</code>",
    uz: "Bu nima chiqaradi? <code>int x = 0; if (x) cout << \"A\"; else cout << \"B\";</code>",
    ru: "Что выведет: <code>int x = 0; if (x) cout << \"A\"; else cout << \"B\";</code>",
    opts: [
      { en: "A", uz: "A", ru: "A" },
      { en: "AB", uz: "AB", ru: "AB" },
      { en: "B", uz: "B", ru: "B" },
      { en: "Nothing", uz: "Hech narsa", ru: "Ничего" },
    ],
    correct: 2,
  },
  {
    en: "Which best describes nested if statements?",
    uz: "Ichma-ich if operatorlarini eng yaxshi qaysi tavsiflaydi?",
    ru: "Что лучше всего описывает вложенные if?",
    opts: [
      { en: "Two if's side by side", uz: "Ikkita if yonma-yon", ru: "Два if рядом" },
      { en: "if inside another if", uz: "if ichida boshqa if", ru: "if внутри другого if" },
      { en: "if with multiple conditions", uz: "Bir nechta shartli if", ru: "if с несколькими условиями" },
      { en: "if without braces", uz: "Qavslarsiz if", ru: "if без скобок" },
    ],
    correct: 1,
  },
  {
    en: "What is the OUTPUT? <code>int a = 10, b = 20; if (a > b) cout << a; else cout << b;</code>",
    uz: "NATIJA nima? <code>int a = 10, b = 20; if (a > b) cout << a; else cout << b;</code>",
    ru: "Что ВЫВЕДЕТ программа? <code>int a = 10, b = 20; if (a > b) cout << a; else cout << b;</code>",
    opts: [
      { en: "10", uz: "10", ru: "10" },
      { en: "20", uz: "20", ru: "20" },
      { en: "1020", uz: "1020", ru: "1020" },
      { en: "Error", uz: "Xato", ru: "Ошибка" },
    ],
    correct: 1,
  },
  {
    en: "<code>switch</code> works with which types?",
    uz: "<code>switch</code> qaysi turlar bilan ishlaydi?",
    ru: "С какими типами работает <code>switch</code>?",
    opts: [
      { en: "string only", uz: "Faqat string", ru: "Только string" },
      { en: "Integer types and char", uz: "Butun turlar va char", ru: "Целочисленные типы и char" },
      { en: "All types", uz: "Barcha turlar", ru: "Все типы" },
      { en: "double only", uz: "Faqat double", ru: "Только double" },
    ],
    correct: 1,
  },

  // ---- LOOPS (12 questions) ----
  {
    en: "How many times does this run? <code>for (int i = 0; i < 5; i++) {}</code>",
    uz: "Bu necha marta bajariladi? <code>for (int i = 0; i < 5; i++) {}</code>",
    ru: "Сколько раз выполнится этот цикл? <code>for (int i = 0; i < 5; i++) {}</code>",
    opts: [
      { en: "4", uz: "4", ru: "4" },
      { en: "6", uz: "6", ru: "6" },
      { en: "5", uz: "5", ru: "5" },
      { en: "Infinite", uz: "Cheksiz", ru: "Бесконечно" },
    ],
    correct: 2,
  },
  {
    en: "Which is an infinite for-loop?",
    uz: "Cheksiz for-sikl qaysi?",
    ru: "Какой цикл for является бесконечным?",
    opts: [
      { en: "for (int i = 0; i < 10; i++)", uz: "for (int i = 0; i < 10; i++)", ru: "for (int i = 0; i < 10; i++)" },
      { en: "for (;;)", uz: "for (;;)", ru: "for (;;)" },
      { en: "for (int i = 10; i > 0; i--)", uz: "for (int i = 10; i > 0; i--)", ru: "for (int i = 10; i > 0; i--)" },
      { en: "for (int i = 0; i < 1; i++)", uz: "for (int i = 0; i < 1; i++)", ru: "for (int i = 0; i < 1; i++)" },
    ],
    correct: 1,
  },
  {
    en: "What does <code>break</code> do in a loop?",
    uz: "Sikl ichida <code>break</code> nima qiladi?",
    ru: "Что делает <code>break</code> в цикле?",
    opts: [
      { en: "Pauses the loop", uz: "Siklni to'xtatib turadi", ru: "Приостанавливает цикл" },
      { en: "Skips one iteration", uz: "Bitta iteratsiyani o'tkazib yuboradi", ru: "Пропускает одну итерацию" },
      { en: "Exits the loop entirely", uz: "Sikldan butunlay chiqadi", ru: "Полностью выходит из цикла" },
      { en: "Restarts the loop", uz: "Siklni qayta boshlaydi", ru: "Перезапускает цикл" },
    ],
    correct: 2,
  },
  {
    en: "What does <code>continue</code> do?",
    uz: "<code>continue</code> nima qiladi?",
    ru: "Что делает <code>continue</code>?",
    opts: [
      { en: "Exits the loop", uz: "Sikldan chiqadi", ru: "Выходит из цикла" },
      { en: "Skips to the next iteration", uz: "Keyingi iteratsiyaga o'tadi", ru: "Переходит к следующей итерации" },
      { en: "Continues after error", uz: "Xatodan keyin davom etadi", ru: "Продолжает после ошибки" },
      { en: "Restarts the program", uz: "Dasturni qayta boshlaydi", ru: "Перезапускает программу" },
    ],
    correct: 1,
  },
  {
    en: "Which loop runs at LEAST once?",
    uz: "Qaysi sikl KAMIDA bir marta bajariladi?",
    ru: "Какой цикл выполняется ХОТЯ БЫ один раз?",
    opts: [
      { en: "for", uz: "for", ru: "for" },
      { en: "while", uz: "while", ru: "while" },
      { en: "do-while", uz: "do-while", ru: "do-while" },
      { en: "None of them", uz: "Hech qaysi", ru: "Никакой" },
    ],
    correct: 2,
  },
  {
    en: "Output: <code>int i = 0; while (i < 3) { cout << i; i++; }</code>",
    uz: "Natija: <code>int i = 0; while (i < 3) { cout << i; i++; }</code>",
    ru: "Что выведет: <code>int i = 0; while (i < 3) { cout << i; i++; }</code>",
    opts: [
      { en: "123", uz: "123", ru: "123" },
      { en: "012", uz: "012", ru: "012" },
      { en: "0123", uz: "0123", ru: "0123" },
      { en: "Infinite loop", uz: "Cheksiz sikl", ru: "Бесконечный цикл" },
    ],
    correct: 1,
  },
  {
    en: "What's wrong? <code>for (int i = 0; i < 5; ) { cout << i; }</code>",
    uz: "Xatolik nimada? <code>for (int i = 0; i < 5; ) { cout << i; }</code>",
    ru: "В чём ошибка? <code>for (int i = 0; i < 5; ) { cout << i; }</code>",
    opts: [
      { en: "No update - infinite loop", uz: "Yangilash yo'q - cheksiz sikl", ru: "Нет обновления - бесконечный цикл" },
      { en: "Wrong syntax", uz: "Noto'g'ri sintaksis", ru: "Неверный синтаксис" },
      { en: "Cannot use cout", uz: "cout ni ishlatib bo'lmaydi", ru: "Нельзя использовать cout" },
      { en: "Nothing wrong", uz: "Xatolik yo'q", ru: "Ошибки нет" },
    ],
    correct: 0,
  },
  {
    en: "How many times prints? <code>for (int i = 1; i <= 4; i++) cout << \"X\";</code>",
    uz: "Necha marta chiqadi? <code>for (int i = 1; i <= 4; i++) cout << \"X\";</code>",
    ru: "Сколько раз выведет? <code>for (int i = 1; i <= 4; i++) cout << \"X\";</code>",
    opts: [
      { en: "3", uz: "3", ru: "3" },
      { en: "4", uz: "4", ru: "4" },
      { en: "5", uz: "5", ru: "5" },
      { en: "Infinite", uz: "Cheksiz", ru: "Бесконечно" },
    ],
    correct: 1,
  },
  {
    en: "Which sums 1+2+...+100 correctly?",
    uz: "1+2+...+100 ni qaysi to'g'ri yig'adi?",
    ru: "Что правильно вычисляет 1+2+...+100?",
    opts: [
      { en: "for (int i = 0; i < 100; i++) sum += i;", uz: "for (int i = 0; i < 100; i++) sum += i;", ru: "for (int i = 0; i < 100; i++) sum += i;" },
      { en: "for (int i = 1; i <= 100; i++) sum += i;", uz: "for (int i = 1; i <= 100; i++) sum += i;", ru: "for (int i = 1; i <= 100; i++) sum += i;" },
      { en: "for (int i = 1; i < 100; i++) sum += i;", uz: "for (int i = 1; i < 100; i++) sum += i;", ru: "for (int i = 1; i < 100; i++) sum += i;" },
      { en: "while (i < 100) sum += i;", uz: "while (i < 100) sum += i;", ru: "while (i < 100) sum += i;" },
    ],
    correct: 1,
  },
  {
    en: "Output: <code>for (int i = 5; i > 2; i--) cout << i;</code>",
    uz: "Natija: <code>for (int i = 5; i > 2; i--) cout << i;</code>",
    ru: "Что выведет: <code>for (int i = 5; i > 2; i--) cout << i;</code>",
    opts: [
      { en: "234", uz: "234", ru: "234" },
      { en: "543", uz: "543", ru: "543" },
      { en: "321", uz: "321", ru: "321" },
      { en: "5432", uz: "5432", ru: "5432" },
    ],
    correct: 1,
  },
  {
    en: "Which loop is BEST when count is unknown?",
    uz: "Soni noma'lum bo'lsa, qaysi sikl ENG YAXSHI?",
    ru: "Какой цикл ЛУЧШЕ всего, когда количество итераций неизвестно?",
    opts: [
      { en: "for", uz: "for", ru: "for" },
      { en: "while", uz: "while", ru: "while" },
      { en: "do-while", uz: "do-while", ru: "do-while" },
      { en: "range-based for", uz: "range-based for", ru: "range-based for" },
    ],
    correct: 1,
  },
  {
    en: "Which is a NESTED loop?",
    uz: "Qaysi ICHMA-ICH sikl?",
    ru: "Что является ВЛОЖЕННЫМ циклом?",
    opts: [
      { en: "Two for's in a row", uz: "Yonma-yon ikkita for", ru: "Два for подряд" },
      { en: "A for loop with break", uz: "break li for sikl", ru: "Цикл for с break" },
      { en: "A loop inside another loop", uz: "Sikl ichidagi boshqa sikl", ru: "Цикл внутри другого цикла" },
      { en: "A loop with continue", uz: "continue li sikl", ru: "Цикл с continue" },
    ],
    correct: 2,
  },

  // ---- FUNCTIONS (10 questions) ----
  {
    en: "Which is a function declaration?",
    uz: "Qaysi funksiya e'loni?",
    ru: "Что является объявлением функции?",
    opts: [
      { en: "int sum;", uz: "int sum;", ru: "int sum;" },
      { en: "int sum(int a, int b);", uz: "int sum(int a, int b);", ru: "int sum(int a, int b);" },
      { en: "sum = 5;", uz: "sum = 5;", ru: "sum = 5;" },
      { en: "function sum(a, b)", uz: "function sum(a, b)", ru: "function sum(a, b)" },
    ],
    correct: 1,
  },
  {
    en: "What does <code>void</code> mean as a return type?",
    uz: "Qaytaruvchi tur sifatida <code>void</code> nimani anglatadi?",
    ru: "Что означает <code>void</code> как тип возвращаемого значения?",
    opts: [
      { en: "Returns 0", uz: "0 qaytaradi", ru: "Возвращает 0" },
      { en: "Returns nothing", uz: "Hech narsa qaytarmaydi", ru: "Не возвращает ничего" },
      { en: "Returns null", uz: "null qaytaradi", ru: "Возвращает null" },
      { en: "Returns void value", uz: "void qiymat qaytaradi", ru: "Возвращает значение void" },
    ],
    correct: 1,
  },
  {
    en: "What does <code>return 5;</code> do in a function?",
    uz: "Funksiyada <code>return 5;</code> nima qiladi?",
    ru: "Что делает <code>return 5;</code> в функции?",
    opts: [
      { en: "Prints 5", uz: "5 ni chiqaradi", ru: "Выводит 5" },
      { en: "Sets a variable to 5", uz: "O'zgaruvchini 5 ga o'rnatadi", ru: "Устанавливает переменную в 5" },
      { en: "Sends 5 back to caller and exits", uz: "5 ni chaqiruvchiga qaytaradi va chiqadi", ru: "Возвращает 5 вызывающему коду и выходит" },
      { en: "Skips to next line", uz: "Keyingi qatorga o'tadi", ru: "Переходит к следующей строке" },
    ],
    correct: 2,
  },
  {
    en: "Output: <code>int f(int x) { return x * 2; } cout << f(7);</code>",
    uz: "Natija: <code>int f(int x) { return x * 2; } cout << f(7);</code>",
    ru: "Что выведет: <code>int f(int x) { return x * 2; } cout << f(7);</code>",
    opts: [
      { en: "7", uz: "7", ru: "7" },
      { en: "9", uz: "9", ru: "9" },
      { en: "14", uz: "14", ru: "14" },
      { en: "0", uz: "0", ru: "0" },
    ],
    correct: 2,
  },
  {
    en: "How is a function CALLED?",
    uz: "Funksiya qanday CHAQIRILADI?",
    ru: "Как ВЫЗЫВАЕТСЯ функция?",
    opts: [
      { en: "call functionName", uz: "call functionName", ru: "call functionName" },
      { en: "functionName(arguments)", uz: "functionName(arguments)", ru: "functionName(arguments)" },
      { en: "functionName[arguments]", uz: "functionName[arguments]", ru: "functionName[arguments]" },
      { en: "def functionName", uz: "def functionName", ru: "def functionName" },
    ],
    correct: 1,
  },
  {
    en: "What are FUNCTION PARAMETERS?",
    uz: "FUNKSIYA PARAMETRLARI nima?",
    ru: "Что такое ПАРАМЕТРЫ ФУНКЦИИ?",
    opts: [
      { en: "Variables in main", uz: "main dagi o'zgaruvchilar", ru: "Переменные в main" },
      { en: "Inputs declared in the function definition", uz: "Funksiya ta'rifida e'lon qilingan kirishlar", ru: "Входные данные, объявленные в определении функции" },
      { en: "The return value", uz: "Qaytaruvchi qiymat", ru: "Возвращаемое значение" },
      { en: "Comments inside function", uz: "Funksiya ichidagi izohlar", ru: "Комментарии внутри функции" },
    ],
    correct: 1,
  },
  {
    en: "Can a function have NO parameters?",
    uz: "Funksiyada parametrlar BO'LMASLIGI mumkinmi?",
    ru: "Может ли функция НЕ иметь параметров?",
    opts: [
      { en: "No, must have at least 1", uz: "Yo'q, kamida 1 ta bo'lishi kerak", ru: "Нет, должен быть хотя бы 1" },
      { en: "Yes - declare with empty ()", uz: "Ha - bo'sh () bilan e'lon qiling", ru: "Да - объявить с пустыми ()" },
      { en: "Only main can", uz: "Faqat main qila oladi", ru: "Только main может" },
      { en: "No, must have 2+", uz: "Yo'q, 2+ bo'lishi kerak", ru: "Нет, должно быть 2+" },
    ],
    correct: 1,
  },
  {
    en: "What is FUNCTION OVERLOADING?",
    uz: "FUNKSIYA OVERLOADING nima?",
    ru: "Что такое ПЕРЕГРУЗКА ФУНКЦИЙ?",
    opts: [
      { en: "Calling the same function twice", uz: "Bir funksiyani ikki marta chaqirish", ru: "Двойной вызов одной функции" },
      { en: "Multiple functions with the same name but different parameters", uz: "Bir xil nomli, lekin turli parametrlarga ega bir nechta funksiya", ru: "Несколько функций с одинаковым именем, но разными параметрами" },
      { en: "A function that overflows memory", uz: "Xotirani to'ldiradigan funksiya", ru: "Функция, переполняющая память" },
      { en: "A function with too many lines", uz: "Juda ko'p qatorli funksiya", ru: "Функция со слишком многими строками" },
    ],
    correct: 1,
  },
  {
    en: "What is RECURSION?",
    uz: "REKURSIYA nima?",
    ru: "Что такое РЕКУРСИЯ?",
    opts: [
      { en: "A function that calls itself", uz: "O'zini chaqiradigan funksiya", ru: "Функция, которая вызывает себя" },
      { en: "A loop", uz: "Sikl", ru: "Цикл" },
      { en: "A function with multiple parameters", uz: "Bir nechta parametrli funksiya", ru: "Функция с несколькими параметрами" },
      { en: "A function returning array", uz: "Massiv qaytaradigan funksiya", ru: "Функция, возвращающая массив" },
    ],
    correct: 0,
  },
  {
    en: "Pass-by-VALUE means:",
    uz: "Qiymat bo'yicha (pass-by-VALUE) o'tkazish:",
    ru: "Передача по ЗНАЧЕНИЮ означает:",
    opts: [
      { en: "Original variable changes", uz: "Asl o'zgaruvchi o'zgaradi", ru: "Изменяется оригинальная переменная" },
      { en: "Function gets a COPY of the value", uz: "Funksiya qiymatning NUSXASINI oladi", ru: "Функция получает КОПИЮ значения" },
      { en: "Address is passed", uz: "Manzil uzatiladi", ru: "Передаётся адрес" },
      { en: "Same as pass-by-reference", uz: "Pass-by-reference bilan bir xil", ru: "То же, что и передача по ссылке" },
    ],
    correct: 1,
  },

  // ---- 1D ARRAYS (14 questions) ----
  {
    en: "Which declares an array of 5 integers?",
    uz: "5 ta butun sonli massivni qaysi e'lon qiladi?",
    ru: "Что объявляет массив из 5 целых чисел?",
    opts: [
      { en: "int arr[5];", uz: "int arr[5];", ru: "int arr[5];" },
      { en: "int arr(5);", uz: "int arr(5);", ru: "int arr(5);" },
      { en: "array<int> arr(5);", uz: "array<int> arr(5);", ru: "array<int> arr(5);" },
      { en: "int 5 arr;", uz: "int 5 arr;", ru: "int 5 arr;" },
    ],
    correct: 0,
  },
  {
    en: "What is the FIRST INDEX of an array?",
    uz: "Massivning BIRINCHI INDEKSI nima?",
    ru: "Каков ПЕРВЫЙ ИНДЕКС массива?",
    opts: [
      { en: "1", uz: "1", ru: "1" },
      { en: "0", uz: "0", ru: "0" },
      { en: "-1", uz: "-1", ru: "-1" },
      { en: "Depends on declaration", uz: "E'longa bog'liq", ru: "Зависит от объявления" },
    ],
    correct: 1,
  },
  {
    en: "Output: <code>int a[3] = {10, 20, 30}; cout << a[1];</code>",
    uz: "Natija: <code>int a[3] = {10, 20, 30}; cout << a[1];</code>",
    ru: "Что выведет: <code>int a[3] = {10, 20, 30}; cout << a[1];</code>",
    opts: [
      { en: "10", uz: "10", ru: "10" },
      { en: "20", uz: "20", ru: "20" },
      { en: "30", uz: "30", ru: "30" },
      { en: "Error", uz: "Xato", ru: "Ошибка" },
    ],
    correct: 1,
  },
  {
    en: "What's wrong? <code>int a[5]; a[5] = 10;</code>",
    uz: "Xatolik nimada? <code>int a[5]; a[5] = 10;</code>",
    ru: "В чём ошибка? <code>int a[5]; a[5] = 10;</code>",
    opts: [
      { en: "Out of bounds - valid indices are 0-4", uz: "Chegaradan chiqgan - yaroqli 0-4", ru: "Вне границ - допустимы 0-4" },
      { en: "Wrong syntax", uz: "Noto'g'ri sintaksis", ru: "Неверный синтаксис" },
      { en: "Need 'new'", uz: "'new' kerak", ru: "Нужно 'new'" },
      { en: "Nothing wrong", uz: "Xatolik yo'q", ru: "Ошибки нет" },
    ],
    correct: 0,
  },
  {
    en: "Initialize all 4 elements to 0:",
    uz: "Hammasi 4 elementni 0 ga o'rnatish:",
    ru: "Инициализировать все 4 элемента нулями:",
    opts: [
      { en: "int a[4] = {};", uz: "int a[4] = {};", ru: "int a[4] = {};" },
      { en: "int a[4] = 0;", uz: "int a[4] = 0;", ru: "int a[4] = 0;" },
      { en: "int a(4) = 0;", uz: "int a(4) = 0;", ru: "int a(4) = 0;" },
      { en: "int a = [0, 0, 0, 0];", uz: "int a = [0, 0, 0, 0];", ru: "int a = [0, 0, 0, 0];" },
    ],
    correct: 0,
  },
  {
    en: "Correct loop through int arr[10]:",
    uz: "int arr[10] bo'ylab to'g'ri sikl:",
    ru: "Правильный обход int arr[10]:",
    opts: [
      { en: "for (int i = 1; i <= 10; i++)", uz: "for (int i = 1; i <= 10; i++)", ru: "for (int i = 1; i <= 10; i++)" },
      { en: "for (int i = 0; i < 10; i++)", uz: "for (int i = 0; i < 10; i++)", ru: "for (int i = 0; i < 10; i++)" },
      { en: "for (int i = 0; i <= 10; i++)", uz: "for (int i = 0; i <= 10; i++)", ru: "for (int i = 0; i <= 10; i++)" },
      { en: "for (int i in arr)", uz: "for (int i in arr)", ru: "for (int i in arr)" },
    ],
    correct: 1,
  },
  {
    en: "How to find the size of int a[10]?",
    uz: "int a[10] o'lchamini qanday topish?",
    ru: "Как найти размер int a[10]?",
    opts: [
      { en: "a.size()", uz: "a.size()", ru: "a.size()" },
      { en: "a.length", uz: "a.length", ru: "a.length" },
      { en: "sizeof(a) / sizeof(a[0])", uz: "sizeof(a) / sizeof(a[0])", ru: "sizeof(a) / sizeof(a[0])" },
      { en: "a.length()", uz: "a.length()", ru: "a.length()" },
    ],
    correct: 2,
  },
  {
    en: "Which finds the MAX in int arr[5]?",
    uz: "int arr[5] dagi MAKSIMUMNI qaysi topadi?",
    ru: "Что находит МАКСИМУМ в int arr[5]?",
    opts: [
      { en: "Loop with comparison", uz: "Solishtirish bilan sikl", ru: "Цикл со сравнением" },
      { en: "arr.max()", uz: "arr.max()", ru: "arr.max()" },
      { en: "max(arr)", uz: "max(arr)", ru: "max(arr)" },
      { en: "arr.find_max()", uz: "arr.find_max()", ru: "arr.find_max()" },
    ],
    correct: 0,
  },
  {
    en: "Output: <code>int a[] = {2, 4, 6, 8}; cout << a[2];</code>",
    uz: "Natija: <code>int a[] = {2, 4, 6, 8}; cout << a[2];</code>",
    ru: "Что выведет: <code>int a[] = {2, 4, 6, 8}; cout << a[2];</code>",
    opts: [
      { en: "4", uz: "4", ru: "4" },
      { en: "8", uz: "8", ru: "8" },
      { en: "2", uz: "2", ru: "2" },
      { en: "6", uz: "6", ru: "6" },
    ],
    correct: 3,
  },
  {
    en: "Sum the array: <code>int a[3] = {1, 2, 3}; int s = 0;</code>",
    uz: "Massivni yig'ish: <code>int a[3] = {1, 2, 3}; int s = 0;</code>",
    ru: "Сумма массива: <code>int a[3] = {1, 2, 3}; int s = 0;</code>",
    opts: [
      { en: "for (i=0; i<3; i++) s = a[i];", uz: "for (i=0; i<3; i++) s = a[i];", ru: "for (i=0; i<3; i++) s = a[i];" },
      { en: "for (i=0; i<3; i++) s += a[i];", uz: "for (i=0; i<3; i++) s += a[i];", ru: "for (i=0; i<3; i++) s += a[i];" },
      { en: "s = a[3];", uz: "s = a[3];", ru: "s = a[3];" },
      { en: "s = sum(a);", uz: "s = sum(a);", ru: "s = sum(a);" },
    ],
    correct: 1,
  },
  {
    en: "Which is the LAST index of int a[7]?",
    uz: "int a[7] ning OXIRGI indeksi qaysi?",
    ru: "Каков ПОСЛЕДНИЙ индекс int a[7]?",
    opts: [
      { en: "7", uz: "7", ru: "7" },
      { en: "6", uz: "6", ru: "6" },
      { en: "8", uz: "8", ru: "8" },
      { en: "0", uz: "0", ru: "0" },
    ],
    correct: 1,
  },
  {
    en: "How to count zeros in int a[n]?",
    uz: "int a[n] da nollar sonini qanday hisoblash?",
    ru: "Как посчитать нули в int a[n]?",
    opts: [
      { en: "a.count(0)", uz: "a.count(0)", ru: "a.count(0)" },
      { en: "Loop and increment counter when a[i] == 0", uz: "Sikl orqali a[i] == 0 da hisoblagichni oshirish", ru: "Цикл с инкрементом счётчика при a[i] == 0" },
      { en: "count(a, 0)", uz: "count(a, 0)", ru: "count(a, 0)" },
      { en: "a.zeros()", uz: "a.zeros()", ru: "a.zeros()" },
    ],
    correct: 1,
  },
  {
    en: "Pass int arr[10] to a function:",
    uz: "int arr[10] ni funksiyaga uzatish:",
    ru: "Передать int arr[10] в функцию:",
    opts: [
      { en: "void f(int arr[])", uz: "void f(int arr[])", ru: "void f(int arr[])" },
      { en: "void f(arr int[10])", uz: "void f(arr int[10])", ru: "void f(arr int[10])" },
      { en: "void f(array arr)", uz: "void f(array arr)", ru: "void f(array arr)" },
      { en: "void f(arr)", uz: "void f(arr)", ru: "void f(arr)" },
    ],
    correct: 0,
  },
  {
    en: "Output: <code>int a[] = {5, 10, 15, 20}; cout << a[0] + a[3];</code>",
    uz: "Natija: <code>int a[] = {5, 10, 15, 20}; cout << a[0] + a[3];</code>",
    ru: "Что выведет: <code>int a[] = {5, 10, 15, 20}; cout << a[0] + a[3];</code>",
    opts: [
      { en: "15", uz: "15", ru: "15" },
      { en: "20", uz: "20", ru: "20" },
      { en: "25", uz: "25", ru: "25" },
      { en: "5", uz: "5", ru: "5" },
    ],
    correct: 2,
  },

  // ---- STRINGS (14 questions) ----
  {
    en: "Which header is needed for <code>string</code> in C++?",
    uz: "C++ da <code>string</code> uchun qaysi header kerak?",
    ru: "Какой заголовочный файл нужен для <code>string</code> в C++?",
    opts: [
      { en: "<iostream>", uz: "<iostream>", ru: "<iostream>" },
      { en: "<string>", uz: "<string>", ru: "<string>" },
      { en: "<cstring>", uz: "<cstring>", ru: "<cstring>" },
      { en: "<text>", uz: "<text>", ru: "<text>" },
    ],
    correct: 1,
  },
  {
    en: "Why use <code>getline(cin, name)</code> instead of <code>cin >> name</code>?",
    uz: "Nima uchun <code>cin >> name</code> o'rniga <code>getline(cin, name)</code> ishlatamiz?",
    ru: "Зачем использовать <code>getline(cin, name)</code> вместо <code>cin >> name</code>?",
    opts: [
      { en: "It is faster", uz: "U tezroq", ru: "Он быстрее" },
      { en: "Reads numbers only", uz: "Faqat sonlarni o'qiydi", ru: "Читает только числа" },
      { en: "Reads full line with spaces", uz: "Bo'shliqlar bilan to'liq qatorni o'qiydi", ru: "Читает всю строку, включая пробелы" },
      { en: "It sorts the string", uz: "Satrni saralaydi", ru: "Сортирует строку" },
    ],
    correct: 2,
  },
  {
    en: "What does <code>s.length()</code> return for <code>string s = \"hello\"</code>?",
    uz: "<code>string s = \"hello\"</code> uchun <code>s.length()</code> nima qaytaradi?",
    ru: "Что возвращает <code>s.length()</code> для <code>string s = \"hello\"</code>?",
    opts: [
      { en: "4", uz: "4", ru: "4" },
      { en: "5", uz: "5", ru: "5" },
      { en: "6", uz: "6", ru: "6" },
      { en: "0", uz: "0", ru: "0" },
    ],
    correct: 1,
  },
  {
    en: "How to access the first character of string <code>s</code>?",
    uz: "<code>s</code> satrining birinchi belgisiga qanday kirish mumkin?",
    ru: "Как получить доступ к первому символу строки <code>s</code>?",
    opts: [
      { en: "s(0)", uz: "s(0)", ru: "s(0)" },
      { en: "s.first()", uz: "s.first()", ru: "s.first()" },
      { en: "s[0]", uz: "s[0]", ru: "s[0]" },
      { en: "s[1]", uz: "s[1]", ru: "s[1]" },
    ],
    correct: 2,
  },
  {
    en: "How to concatenate two strings <code>a</code> and <code>b</code>?",
    uz: "<code>a</code> va <code>b</code> satrlarini qanday birlashtirish mumkin?",
    ru: "Как соединить две строки <code>a</code> и <code>b</code>?",
    opts: [
      { en: "a + b", uz: "a + b", ru: "a + b" },
      { en: "a.add(b)", uz: "a.add(b)", ru: "a.add(b)" },
      { en: "concat(a, b)", uz: "concat(a, b)", ru: "concat(a, b)" },
      { en: "a & b", uz: "a & b", ru: "a & b" },
    ],
    correct: 0,
  },
  {
    en: "What does <code>s.empty()</code> return for an empty string?",
    uz: "Bo'sh satr uchun <code>s.empty()</code> nima qaytaradi?",
    ru: "Что возвращает <code>s.empty()</code> для пустой строки?",
    opts: [
      { en: "0", uz: "0", ru: "0" },
      { en: "true", uz: "true", ru: "true" },
      { en: "false", uz: "false", ru: "false" },
      { en: "Error", uz: "Xato", ru: "Ошибка" },
    ],
    correct: 1,
  },
  {
    en: "How many characters are in the text string <code>\"C++\"</code>?",
    uz: "<code>\"C++\"</code> text stringida nechta belgi bor?",
    ru: "Сколько символов в строке <code>\"C++\"</code>?",
    opts: [
      { en: "2", uz: "2", ru: "2" },
      { en: "3", uz: "3", ru: "3" },
      { en: "4", uz: "4", ru: "4" },
      { en: "5", uz: "5", ru: "5" },
    ],
    correct: 1,
  },
  {
    en: "What does <code>cin >> word;</code> stop at?",
    uz: "<code>cin >> word;</code> nimada to'xtaydi?",
    ru: "На чём останавливается <code>cin >> word;</code>?",
    opts: [
      { en: "Period", uz: "Nuqta", ru: "На точке" },
      { en: "Whitespace (space/tab/newline)", uz: "Bo'shliq (space/tab/newline)", ru: "На пробельных символах (пробел/таб/новая строка)" },
      { en: "A vowel", uz: "Unli harf", ru: "На гласной" },
      { en: "Never stops", uz: "Hech qachon to'xtamaydi", ru: "Никогда не останавливается" },
    ],
    correct: 1,
  },
  {
    en: "Which is a string literal in C++?",
    uz: "C++ da qaysi satr literal?",
    ru: "Что является строковым литералом в C++?",
    opts: [
      { en: "'hello'", uz: "'hello'", ru: "'hello'" },
      { en: "\"hello\"", uz: "\"hello\"", ru: "\"hello\"" },
      { en: "`hello`", uz: "`hello`", ru: "`hello`" },
      { en: "hello", uz: "hello", ru: "hello" },
    ],
    correct: 1,
  },
  {
    en: "What does <code>s.substr(1, 3)</code> return for <code>s = \"HELLO\"</code>?",
    uz: "<code>s = \"HELLO\"</code> uchun <code>s.substr(1, 3)</code> nima qaytaradi?",
    ru: "Что возвращает <code>s.substr(1, 3)</code> для <code>s = \"HELLO\"</code>?",
    opts: [
      { en: "HEL", uz: "HEL", ru: "HEL" },
      { en: "ELL", uz: "ELL", ru: "ELL" },
      { en: "LLO", uz: "LLO", ru: "LLO" },
      { en: "HELLO", uz: "HELLO", ru: "HELLO" },
    ],
    correct: 1,
  },
  {
    en: "How do you check if a character <code>c</code> is an uppercase letter (using ASCII)?",
    uz: "ASCII orqali <code>c</code> belgi katta harf ekanligini qanday tekshirasiz?",
    ru: "Как проверить, является ли символ <code>c</code> заглавной буквой (через ASCII)?",
    opts: [
      { en: "c >= 'A' && c <= 'Z'", uz: "c >= 'A' && c <= 'Z'", ru: "c >= 'A' && c <= 'Z'" },
      { en: "c > 65 && c > 90", uz: "c > 65 && c > 90", ru: "c > 65 && c > 90" },
      { en: "c.upper()", uz: "c.upper()", ru: "c.upper()" },
      { en: "c >= 'a' && c <= 'z'", uz: "c >= 'a' && c <= 'z'", ru: "c >= 'a' && c <= 'z'" },
    ],
    correct: 0,
  },
  {
    en: "What is stored in <code>s</code> after: <code>string s = \"abc\"; s += \"de\";</code>?",
    uz: "<code>string s = \"abc\"; s += \"de\";</code> keyin s da nima saqlanadi?",
    ru: "Что хранится в <code>s</code> после: <code>string s = \"abc\"; s += \"de\";</code>?",
    opts: [
      { en: "abc", uz: "abc", ru: "abc" },
      { en: "de", uz: "de", ru: "de" },
      { en: "abcde", uz: "abcde", ru: "abcde" },
      { en: "deabc", uz: "deabc", ru: "deabc" },
    ],
    correct: 2,
  },
  {
    en: "To loop through each character of a string s, a correct for is:",
    uz: "s satrining har bir belgisidan o'tish uchun to'g'ri for:",
    ru: "Чтобы пройти по каждому символу строки s, правильный for:",
    opts: [
      { en: "for (int i = 0; i < s.size(); i++)", uz: "for (int i = 0; i < s.size(); i++)", ru: "for (int i = 0; i < s.size(); i++)" },
      { en: "for (int i = 1; i <= s.length(); i++)", uz: "for (int i = 1; i <= s.length(); i++)", ru: "for (int i = 1; i <= s.length(); i++)" },
      { en: "for (int i = 0; i <= s.length(); i++)", uz: "for (int i = 0; i <= s.length(); i++)", ru: "for (int i = 0; i <= s.length(); i++)" },
      { en: "for (int i in s)", uz: "for (int i in s)", ru: "for (int i in s)" },
    ],
    correct: 0,
  },
  {
    en: "What is the output? <code>string s = \"Hi\"; cout << s[1];</code>",
    uz: "Natija nima? <code>string s = \"Hi\"; cout << s[1];</code>",
    ru: "Что выведет программа? <code>string s = \"Hi\"; cout << s[1];</code>",
    opts: [
      { en: "H", uz: "H", ru: "H" },
      { en: "i", uz: "i", ru: "i" },
      { en: "Hi", uz: "Hi", ru: "Hi" },
      { en: "1", uz: "1", ru: "1" },
    ],
    correct: 1,
  },

  // ---- TYPE CONVERSION (5 questions, explicit & implicit) ----
  {
    en: "Which of these is an <b>explicit</b> type conversion in C++?",
    uz: "Qaysi biri C++ da <b>aniq</b> tur o'zgartirish hisoblanadi?",
    ru: "Что из перечисленного является <b>явным</b> преобразованием типа в C++?",
    opts: [
      { en: "int x = 3.7;", uz: "int x = 3.7;", ru: "int x = 3.7;" },
      { en: "double y = 5;", uz: "double y = 5;", ru: "double y = 5;" },
      { en: "int x = (int)3.7;", uz: "int x = (int)3.7;", ru: "int x = (int)3.7;" },
      { en: "int x = 3 + 2;", uz: "int x = 3 + 2;", ru: "int x = 3 + 2;" },
    ],
    correct: 2,
  },
  {
    en: "What is the value of <code>x</code>?<br><code>double a = 7.8; int x = (int)a;</code>",
    uz: "<code>x</code> ning qiymati nima?<br><code>double a = 7.8; int x = (int)a;</code>",
    ru: "Каково значение <code>x</code>?<br><code>double a = 7.8; int x = (int)a;</code>",
    opts: [
      { en: "7", uz: "7", ru: "7" },
      { en: "8", uz: "8", ru: "8" },
      { en: "7.8", uz: "7.8", ru: "7.8" },
      { en: "Compile error", uz: "Kompilyatsiya xatosi", ru: "Ошибка компиляции" },
    ],
    correct: 0,
  },
  {
    en: "Implicit conversion happens when:",
    uz: "Implicit (avtomatik) konvertatsiya qachon sodir bo'ladi:",
    ru: "Когда происходит неявное (автоматическое) преобразование?",
    opts: [
      { en: "You use <code>static_cast</code>", uz: "<code>static_cast</code> ishlatilganda", ru: "Когда используется <code>static_cast</code>" },
      { en: "Compiler converts smaller to bigger type automatically", uz: "Kompilyator kichik turdan kattaga avtomatik o'tkazganda", ru: "Когда компилятор автоматически преобразует меньший тип в больший" },
      { en: "You write <code>(int)</code> manually", uz: "Qo'lda <code>(int)</code> yozganda", ru: "Когда вручную пишется <code>(int)</code>" },
      { en: "Only inside functions", uz: "Faqat funksiyalar ichida", ru: "Только внутри функций" },
    ],
    correct: 1,
  },
  {
    en: "What does <code>static_cast<double>(5) / 2</code> give?",
    uz: "<code>static_cast<double>(5) / 2</code> nimani beradi?",
    ru: "Что даёт <code>static_cast<double>(5) / 2</code>?",
    opts: [
      { en: "2", uz: "2", ru: "2" },
      { en: "2.5", uz: "2.5", ru: "2.5" },
      { en: "3", uz: "3", ru: "3" },
      { en: "Error", uz: "Xato", ru: "Ошибка" },
    ],
    correct: 1,
  },
  {
    en: "Why use <code>static_cast<int></code> instead of C-style <code>(int)</code>?",
    uz: "Nima uchun C uslubidagi <code>(int)</code> o'rniga <code>static_cast<int></code> ishlatiladi?",
    ru: "Почему используется <code>static_cast<int></code> вместо приведения в стиле C <code>(int)</code>?",
    opts: [
      { en: "It's faster", uz: "U tezroq", ru: "Он быстрее" },
      { en: "It's safer and more explicit", uz: "U xavfsizroq va aniqroq", ru: "Он безопаснее и более явный" },
      { en: "It works at runtime only", uz: "U faqat runtime da ishlaydi", ru: "Он работает только во время выполнения" },
      { en: "They are identical", uz: "Ular bir xil", ru: "Они одинаковы" },
    ],
    correct: 1,
  },

  // ---- FUNCTION OVERLOADING / OVERRIDING (5 questions) ----
  {
    en: "What is function <b>overloading</b>?",
    uz: "Funksiya <b>overloading</b> nima?",
    ru: "Что такое <b>перегрузка</b> функций?",
    opts: [
      { en: "Two functions with same name and same parameters", uz: "Bir xil nomli va parametrli ikki funksiya", ru: "Две функции с одинаковым именем и одинаковыми параметрами" },
      { en: "Two functions with same name but different parameter lists", uz: "Bir xil nomli, lekin turli parametrli ikki funksiya", ru: "Две функции с одинаковым именем, но разными списками параметров" },
      { en: "Calling a function inside itself", uz: "Funksiyani o'zining ichida chaqirish", ru: "Вызов функции внутри самой себя" },
      { en: "Returning multiple values", uz: "Bir nechta qiymat qaytarish", ru: "Возврат нескольких значений" },
    ],
    correct: 1,
  },
  {
    en: "Which is a valid overload pair?",
    uz: "Qaysi overload juftligi to'g'ri?",
    ru: "Какая пара перегруженных функций является корректной?",
    opts: [
      { en: "<code>int f(int)</code> and <code>int f(int)</code>", uz: "<code>int f(int)</code> va <code>int f(int)</code>", ru: "<code>int f(int)</code> и <code>int f(int)</code>" },
      { en: "<code>int f(int)</code> and <code>int f(double)</code>", uz: "<code>int f(int)</code> va <code>int f(double)</code>", ru: "<code>int f(int)</code> и <code>int f(double)</code>" },
      { en: "<code>int f(int)</code> and <code>double f(int)</code>", uz: "<code>int f(int)</code> va <code>double f(int)</code>", ru: "<code>int f(int)</code> и <code>double f(int)</code>" },
      { en: "None", uz: "Hech qaysi", ru: "Никакая" },
    ],
    correct: 1,
  },
  {
    en: "Function overloading is resolved at:",
    uz: "Funksiya overload qilish hal qilinadi:",
    ru: "Перегрузка функций разрешается:",
    opts: [
      { en: "Run time", uz: "Ishga tushirilganda", ru: "Во время выполнения" },
      { en: "Compile time", uz: "Kompilyatsiya vaqtida", ru: "Во время компиляции" },
      { en: "Link time", uz: "Bog'lash vaqtida", ru: "Во время компоновки" },
      { en: "Never", uz: "Hech qachon", ru: "Никогда" },
    ],
    correct: 1,
  },
  {
    en: "Function <b>overriding</b> is mainly about:",
    uz: "Funksiya <b>overriding</b> asosan:",
    ru: "<b>Переопределение</b> функции связано в основном с:",
    opts: [
      { en: "Inheritance and virtual functions", uz: "Meros va virtual funksiyalar", ru: "Наследованием и виртуальными функциями" },
      { en: "Renaming a function", uz: "Funksiyani qayta nomlash", ru: "Переименованием функции" },
      { en: "Calling a function twice", uz: "Funksiyani ikki marta chaqirish", ru: "Двойным вызовом функции" },
      { en: "Returning a different type", uz: "Boshqa tur qaytarish", ru: "Возвратом другого типа" },
    ],
    correct: 0,
  },
  {
    en: "Can two functions overload by return type ALONE?",
    uz: "Ikki funksiya FAQAT qaytaruvchi tur bo'yicha overload bo'la oladimi?",
    ru: "Могут ли две функции перегружаться ТОЛЬКО по типу возвращаемого значения?",
    opts: [
      { en: "Yes, always", uz: "Ha, doim", ru: "Да, всегда" },
      { en: "No", uz: "Yo'q", ru: "Нет" },
      { en: "Only with const", uz: "Faqat const bilan", ru: "Только с const" },
      { en: "Only in classes", uz: "Faqat sinflarda", ru: "Только в классах" },
    ],
    correct: 1,
  },

  // ---- MULTIDIMENSIONAL ARRAYS (5 questions) ----
  {
    en: "How do you declare a 3x4 integer matrix?",
    uz: "3x4 butun sonli matritsani qanday e'lon qilasiz?",
    ru: "Как объявить целочисленную матрицу 3x4?",
    opts: [
      { en: "int m[3,4];", uz: "int m[3,4];", ru: "int m[3,4];" },
      { en: "int m[3][4];", uz: "int m[3][4];", ru: "int m[3][4];" },
      { en: "int m(3)(4);", uz: "int m(3)(4);", ru: "int m(3)(4);" },
      { en: "matrix int m(3,4);", uz: "matrix int m(3,4);", ru: "matrix int m(3,4);" },
    ],
    correct: 1,
  },
  {
    en: "How do you access row 2, column 3 of <code>int m[5][5]</code>?",
    uz: "<code>int m[5][5]</code> ning 2-qator, 3-ustuniga qanday murojaat qilish?",
    ru: "Как обратиться к строке 2, столбцу 3 в <code>int m[5][5]</code>?",
    opts: [
      { en: "m[2,3]", uz: "m[2,3]", ru: "m[2,3]" },
      { en: "m(2)(3)", uz: "m(2)(3)", ru: "m(2)(3)" },
      { en: "m[2][3]", uz: "m[2][3]", ru: "m[2][3]" },
      { en: "m.at(2,3)", uz: "m.at(2,3)", ru: "m.at(2,3)" },
    ],
    correct: 2,
  },
  {
    en: "Output: <code>int m[2][2] = {{1,2},{3,4}}; cout << m[1][0];</code>",
    uz: "Natija: <code>int m[2][2] = {{1,2},{3,4}}; cout << m[1][0];</code>",
    ru: "Что выведет: <code>int m[2][2] = {{1,2},{3,4}}; cout << m[1][0];</code>",
    opts: [
      { en: "1", uz: "1", ru: "1" },
      { en: "2", uz: "2", ru: "2" },
      { en: "3", uz: "3", ru: "3" },
      { en: "4", uz: "4", ru: "4" },
    ],
    correct: 2,
  },
  {
    en: "How many elements does <code>int m[3][4]</code> have?",
    uz: "<code>int m[3][4]</code> ning nechta elementi bor?",
    ru: "Сколько элементов содержит <code>int m[3][4]</code>?",
    opts: [
      { en: "7", uz: "7", ru: "7" },
      { en: "12", uz: "12", ru: "12" },
      { en: "9", uz: "9", ru: "9" },
      { en: "16", uz: "16", ru: "16" },
    ],
    correct: 1,
  },
  {
    en: "Which loop pattern correctly iterates over all elements of <code>int m[3][4]</code>?",
    uz: "Qaysi sikl naqshi <code>int m[3][4]</code> ning barcha elementlari bo'ylab to'g'ri iteratsiya qiladi?",
    ru: "Какой шаблон цикла правильно перебирает все элементы <code>int m[3][4]</code>?",
    opts: [
      { en: "Single for from 0 to 12", uz: "0 dan 12 gacha bitta for", ru: "Один цикл for от 0 до 12" },
      { en: "Nested for: rows 0..3, cols 0..4", uz: "Ichma-ich for: qator 0..3, ustun 0..4", ru: "Вложенный for: строки 0..3, столбцы 0..4" },
      { en: "for i in m", uz: "for i in m", ru: "for i in m" },
      { en: "Recursion", uz: "Rekursiya", ru: "Рекурсия" },
    ],
    correct: 1,
  },

  // ---- RANGE-BASED FOR + DO-WHILE (5 questions) ----
  {
    en: "How do you write a range-based for loop over <code>int arr[5]</code>?",
    uz: "<code>int arr[5]</code> bo'ylab range-based for siklni qanday yozish?",
    ru: "Как написать range-based for цикл по <code>int arr[5]</code>?",
    opts: [
      { en: "for (int x : arr)", uz: "for (int x : arr)", ru: "for (int x : arr)" },
      { en: "for (int x in arr)", uz: "for (int x in arr)", ru: "for (int x in arr)" },
      { en: "foreach (arr as x)", uz: "foreach (arr as x)", ru: "foreach (arr as x)" },
      { en: "for (x = 0; x < arr.size(); x++)", uz: "for (x = 0; x < arr.size(); x++)", ru: "for (x = 0; x < arr.size(); x++)" },
    ],
    correct: 0,
  },
  {
    en: "A <code>do-while</code> loop guarantees the body runs at least:",
    uz: "<code>do-while</code> sikli tanasining kamida necha marta bajarilishini kafolatlaydi:",
    ru: "Цикл <code>do-while</code> гарантирует, что тело выполнится как минимум:",
    opts: [
      { en: "0 times", uz: "0 marta", ru: "0 раз" },
      { en: "1 time", uz: "1 marta", ru: "1 раз" },
      { en: "2 times", uz: "2 marta", ru: "2 раза" },
      { en: "Depends on condition", uz: "Shartga bog'liq", ru: "Зависит от условия" },
    ],
    correct: 1,
  },
  {
    en: "Which loop is BEST when you must check the condition AFTER executing the body?",
    uz: "Tana bajarilgandan KEYIN shartni tekshirish kerak bo'lganda qaysi sikl eng mos?",
    ru: "Какой цикл ЛУЧШЕ всего использовать, когда условие проверяется ПОСЛЕ выполнения тела?",
    opts: [
      { en: "<code>for</code>", uz: "<code>for</code>", ru: "<code>for</code>" },
      { en: "<code>while</code>", uz: "<code>while</code>", ru: "<code>while</code>" },
      { en: "<code>do-while</code>", uz: "<code>do-while</code>", ru: "<code>do-while</code>" },
      { en: "range-based <code>for</code>", uz: "range-based <code>for</code>", ru: "range-based <code>for</code>" },
    ],
    correct: 2,
  },
  {
    en: "Using a range-based for loop, how do you modify each element of <code>int arr[5]</code>?",
    uz: "Range-based for sikli bilan <code>int arr[5]</code> ning har bir elementini qanday o'zgartirasiz?",
    ru: "Используя range-based for, как изменить каждый элемент <code>int arr[5]</code>?",
    opts: [
      { en: "<code>for (int x : arr) x *= 2;</code>", uz: "<code>for (int x : arr) x *= 2;</code>", ru: "<code>for (int x : arr) x *= 2;</code>" },
      { en: "<code>for (int&amp; x : arr) x *= 2;</code>", uz: "<code>for (int&amp; x : arr) x *= 2;</code>", ru: "<code>for (int&amp; x : arr) x *= 2;</code>" },
      { en: "<code>for (const int x : arr) x *= 2;</code>", uz: "<code>for (const int x : arr) x *= 2;</code>", ru: "<code>for (const int x : arr) x *= 2;</code>" },
      { en: "You cannot modify with range-based for", uz: "Range-based for bilan o'zgartirib bo'lmaydi", ru: "С range-based for изменить нельзя" },
    ],
    correct: 1,
  },
  {
    en: "How many times does this run? <code>int i=0; do { i++; } while (i<3);</code>",
    uz: "Bu necha marta bajariladi? <code>int i=0; do { i++; } while (i<3);</code>",
    ru: "Сколько раз выполнится этот код? <code>int i=0; do { i++; } while (i<3);</code>",
    opts: [
      { en: "2", uz: "2", ru: "2" },
      { en: "3", uz: "3", ru: "3" },
      { en: "4", uz: "4", ru: "4" },
      { en: "Infinite", uz: "Cheksiz", ru: "Бесконечно" },
    ],
    correct: 1,
  },
];
